services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: workera_db
      POSTGRES_HOST_AUTH_METHOD: md5
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    volumes:
     - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superuser -d workera_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local